name: Continous Integration /Continous Ddelivery (CI/CD)

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: |
          docker build \
            --build-arg COMMIT_SHA=${{ github.sha }} \
            -t pipeline-demo:${{ github.sha }} .
